(part "XC6806A42011-G"
    (packageRef "XC6806A42011G")
    (interface
        (port "1" (symbPinId 1) (portName "VIN") (portType INOUT))
        (port "2" (symbPinId 2) (portName "ISET") (portType INOUT))
        (port "3" (symbPinId 3) (portName "THIN") (portType INOUT))
        (port "4" (symbPinId 4) (portName "VREG") (portType INOUT))
        (port "5" (symbPinId 5) (portName "PGB") (portType INOUT))
        (port "6" (symbPinId 6) (portName "CSO") (portType INOUT))
        (port "7" (symbPinId 7) (portName "VSS") (portType INOUT))
        (port "8" (symbPinId 8) (portName "SD") (portType INOUT))
        (port "9" (symbPinId 9) (portName "BAT") (portType INOUT))
        (port "10" (symbPinId 10) (portName "OUT") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Farnell_Part_Number" "")
    (property "Farnell_Price/Stock" "")
    (property "Manufacturer_Name" "Torex")
    (property "Manufacturer_Part_Number" "XC6806A42011-G")
    (property "Description" "Battery Charger Li-Ion/Li-Pol Single Cell 385mA 4.2V 10-Pin LGA-B01 T/R")
    (property "Datasheet_Link" "https://www.torexsemi.com/file/xc6806/XC6806.pdf")
    (property "symbolName1" "XC6806A42011-G")
)
