(part "EE-SX1320"
    (packageRef "EE-SX1320")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "653-EESX1320")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Omron-Electronics/EE-SX1320?qs=D%252BXMYtqGEfctDBBegrcKKA%3D%3D")
    (property "Manufacturer_Name" "OMRON Electronics")
    (property "Manufacturer_Part_Number" "EE-SX1320")
    (property "Description" "Optical Switches, Transmissive, Phototransistor Output SMT, 2mm Transmissive Photo")
    (property "Datasheet_Link" "https://www.omron.com/ecb/products/pdf/en-ee_sx1320.pdf")
    (property "symbolName1" "EE-SX1320")
)
