(part "JS102011SAQN"
    (packageRef "JS102011SAQN")
    (interface
        (port "1" (symbPinId 1) (portName "N.C.") (portType INOUT))
        (port "2" (symbPinId 2) (portName "COM") (portType INOUT))
        (port "3" (symbPinId 3) (portName "N.O.") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "162")
    (property "Farnell_Part_Number" "")
    (property "Farnell_Price/Stock" "")
    (property "Manufacturer_Name" "LITTELFUSE")
    (property "Manufacturer_Part_Number" "JS102011SAQN")
    (property "Description" "Slide Switch SPDT Surface Mount, Right Angle 300mA (DC) 6V Gull Wing -40C ~ 85C")
    (property "Datasheet_Link" "https://www.littelfuse.com/assetdocs/littelfuse-ck-slide-js-series-datasheet?assetguid=aba42b08-0d2c-423b-813d-a2faa5a3bb14")
    (property "symbolName1" "JS102011SAQN")
)
