(part "LSM9DS1TR"
    (packageRef "LGA-24L_3X3_5X1MM_")
    (interface
        (port "1" (symbPinId 1) (portName "VDDIO_1") (portType POWER))
        (port "2" (symbPinId 2) (portName "SCL/SPC") (portType OUTPUT))
        (port "3" (symbPinId 3) (portName "VDDIO_2") (portType POWER))
        (port "4" (symbPinId 4) (portName "SDA/SDI/SDO") (portType INOUT))
        (port "5" (symbPinId 5) (portName "SDO_A/G") (portType OUTPUT))
        (port "6" (symbPinId 6) (portName "SDO_M") (portType OUTPUT))
        (port "7" (symbPinId 7) (portName "CS_A/G") (portType INOUT))
        (port "8" (symbPinId 8) (portName "CS_M") (portType INOUT))
        (port "9" (symbPinId 9) (portName "DRDY_M") (portType INOUT))
        (port "10" (symbPinId 10) (portName "INT_M") (portType INOUT))
        (port "11" (symbPinId 11) (portName "INT1_A/G") (portType INOUT))
        (port "12" (symbPinId 12) (portName "INT2_A/G") (portType INOUT))
        (port "13" (symbPinId 13) (portName "DEN_A/G") (portType INOUT))
        (port "14" (symbPinId 14) (portName "RES_1") (portType GROUND))
        (port "15" (symbPinId 15) (portName "RES_2") (portType GROUND))
        (port "16" (symbPinId 16) (portName "RES_3") (portType GROUND))
        (port "17" (symbPinId 17) (portName "RES_4") (portType GROUND))
        (port "18" (symbPinId 18) (portName "RES_5") (portType GROUND))
        (port "19" (symbPinId 19) (portName "GND_1") (portType GROUND))
        (port "20" (symbPinId 20) (portName "GND_2") (portType GROUND))
        (port "21" (symbPinId 21) (portName "CAP") (portType GROUND))
        (port "22" (symbPinId 22) (portName "VDD_1") (portType POWER))
        (port "23" (symbPinId 23) (portName "VDD_2") (portType POWER))
        (port "24" (symbPinId 24) (portName "C1") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Farnell_Part_Number" "")
    (property "Farnell_Price/Stock" "")
    (property "Manufacturer_Name" "STMicroelectronics")
    (property "Manufacturer_Part_Number" "LSM9DS1TR")
    (property "Description" "iNEMO Inertial 3D Accel/Gyro/Magn. LGA24 STMicroelectronics LSM9DS1TR 3-Axis Accelerometer, Gyroscope & Magnetometer, 0  400 kHz, 1.9  3.6 V")
    (property "Datasheet_Link" "http://www.st.com/content/ccc/resource/technical/document/datasheet/1e/3f/2a/d6/25/eb/48/46/DM00103319.pdf/files/DM00103319.pdf/jcr:content/translations/en.DM00103319.pdf")
    (property "symbolName1" "LSM9DS1TR")
)
